on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install --upgrade build twine

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        run: |
          twine upload --username __token__ \
                       --password ${{ secrets.PYPI_API_TOKEN }} \
                       dist/*